{
 "title": "Story",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Validator Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(1 - (avg(increase(cometbft_consensus_validator_missed_blocks{job=\"story_validator\"}[5m])) by (chain)) / (avg(increase(cometbft_consensus_height{job=\"story_validator\"}[5m])) by (chain))) * 100",
     "legendFormat": "{{chain}} - uptime based on missed blocks"
    },
    {
     "expr": "((avg(increase(cometbft_consensus_validator_last_signed_height{job=\"story_validator\"}[5m])) by (chain)) / (avg(increase(cometbft_consensus_latest_block_height{job=\"story_validator\"}[5m])) by (chain))) * 100",
     "legendFormat": "{{chain}} - signed blocks / all blocks [5m]"
    }
   ]
  },
  {
   "title": "Validator Uptime",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (avg(cometbft_consensus_validator_missed_blocks{job=\"story_validator\"})) / (avg(cometbft_consensus_height{job=\"story_validator\"}))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Voting Power",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(cometbft_consensus_validator_power{job=\"story_validator\"}) / avg(cometbft_consensus_validators_power{job=\"story_validator\"}) * 100",
     "legendFormat": "Validator voting power"
    }
   ]
  },
  {
   "title": "Validator Service Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "up{job=\"story_validator\"}",
     "legendFormat": "{{chain}} - {{ip}}"
    }
   ]
  },
  {
   "title": "Story Validator Free Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/md2\",mountpoint=\"/etc/hosts\"} / 1073741824",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Validator Missed Blocks Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(cometbft_consensus_validator_missed_blocks{job=\"story_validator\"}[1m])",
     "legendFormat": "{{chain}} - {{ip}}"
    }
   ]
  },
  {
   "title": "Story Validator Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{ip=\"176.9.54.69\"}[30d]) + avg_over_time(node_memory_Cached_bytes{ip=\"176.9.54.69\"}[30d]) + avg_over_time(node_memory_Buffers_bytes{ip=\"176.9.54.69\"}[30d])) / avg_over_time(node_memory_MemTotal_bytes{ip=\"176.9.54.69\"}[30d])))",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Validator Sync Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "increase(cometbft_consensus_latest_block_height{job=\"story_validator\"}[1m])",
     "legendFormat": "{{chain}} - {{ip}}"
    }
   ]
  },
  {
   "title": "Story Validator CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "100 - (avg by (ip) (irate(node_cpu_seconds_total{ip=\"176.9.54.69\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Validator Peer Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "cometbft_p2p_peers{job=\"story_validator\"}",
     "legendFormat": "{{chain}} - {{ip}}"
    }
   ]
  }
 ]
}